<?xml version="1.0" encoding="utf-8"?><Database Name="ZBO_CVTRADING" Class="DBMLSapCVtradingDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=alerce;Initial Catalog=ZBO_CVTRADING;User ID=sa" SettingsObjectName="DBTest.Properties.Settings" SettingsPropertyName="ZBO_CVTRADINGConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ORDR" Member="ORDR">
    <Type Name="ORDR">
      <Column Name="DocEntry" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DocNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DocType" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="CANCELED" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Handwrtten" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Printed" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DocStatus" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="InvntSttus" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Transfered" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ObjType" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DocDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DocDueDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CardCode" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="CardName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="NumAtCard" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="VatPercent" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="VatSum" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="VatSumFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DiscPrcnt" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DiscSum" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DiscSumFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DocCur" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="DocRate" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DocTotal" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DocTotalFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="PaidToDate" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="PaidFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="GrosProfit" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="GrosProfFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="Ref1" Type="System.String" DbType="NVarChar(11)" CanBeNull="true" />
      <Column Name="Ref2" Type="System.String" DbType="NVarChar(11)" CanBeNull="true" />
      <Column Name="Comments" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="JrnlMemo" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="TransId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReceiptNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GroupNum" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DocTime" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SlpCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TrnspCode" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="PartSupply" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Confirmed" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="GrossBase" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ImportEnt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateTran" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="SummryType" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="UpdInvnt" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="UpdCardBal" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Instance" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Flags" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InvntDirec" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="CntctCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ShowSCN" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="FatherCard" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="SysRate" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="CurSource" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="VatSumSy" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DiscSumSy" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DocTotalSy" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="PaidSys" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="FatherType" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="GrosProfSy" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsICT" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Volume" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="VolUnit" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Weight" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="WeightUnit" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Series" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TaxDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Filler" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="DataSource" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="StampNum" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="isCrin" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="FinncPriod" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserSign" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="selfInv" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="VatPaid" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="VatPaidFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="VatPaidSys" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="UserSign2" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="WddStatus" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="draftKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalExpns" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="TotalExpFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="TotalExpSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DunnLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Address2" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="LogInstanc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Exported" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="StationID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Indicator" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="NetProc" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="AqcsTax" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="AqcsTaxFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="AqcsTaxSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="CashDiscPr" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="CashDiscnt" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="CashDiscFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="CashDiscSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ShipToCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LicTradNum" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="PaymentRef" Type="System.String" DbType="NVarChar(27)" CanBeNull="true" />
      <Column Name="WTSum" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="WTSumFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="WTSumSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="RoundDif" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="RoundDifFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="RoundDifSy" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="CheckDigit" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Form1099" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Box1099" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="submitted" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="PoPrss" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Rounding" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="RevisionPo" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Segment" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ReqDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CancelDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PickStatus" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Pick" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="BlockDunn" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="PeyMethod" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="PayBlock" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="PayBlckRef" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaxDscn" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Reserve" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Max1099" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="CntrlBnk" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="PickRmrk" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="ISRCodLine" Type="System.String" DbType="NVarChar(53)" CanBeNull="true" />
      <Column Name="ExpAppl" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ExpApplFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ExpApplSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="Project" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DeferrTax" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="LetterNum" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FromDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ToDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="WTApplied" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="WTAppliedF" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="BoeReserev" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="AgentCode" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="WTAppliedS" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="EquVatSum" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="EquVatSumF" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="EquVatSumS" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="Installmnt" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="VATFirst" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="NnSbAmnt" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="NnSbAmntSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="NbSbAmntFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ExepAmnt" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ExepAmntSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ExepAmntFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="VatDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CorrExt" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="CorrInv" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NCorrInv" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CEECFlag" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="BaseAmnt" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="BaseAmntSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="BaseAmntFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="CtlAccount" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="BPLId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BPLName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="VATRegNum" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="TxInvRptNo" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="TxInvRptDt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="KVVATCode" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="WTDetails" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SumAbsId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SumRptDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PIndicator" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ManualNum" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="UseShpdGd" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="BaseVtAt" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="BaseVtAtSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="BaseVtAtFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="NnSbVAt" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="NnSbVAtSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="NbSbVAtFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ExptVAt" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ExptVAtSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ExptVAtFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="LYPmtAt" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="LYPmtAtSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="LYPmtAtFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ExpAnSum" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ExpAnSys" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ExpAnFrgn" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DocSubType" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="DpmStatus" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DpmAmnt" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DpmAmntSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DpmAmntFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DpmDrawn" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DpmPrcnt" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="PaidSum" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="PaidSumFc" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="PaidSumSc" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="FolioPref" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="FolioNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DpmAppl" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DpmApplFc" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DpmApplSc" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="LPgFolioN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Header" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Footer" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Posted" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="OwnerCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BPChCode" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="BPChCntc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PayToCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsPaytoBnk" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="BnkCntry" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="BankCode" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="BnkAccount" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BnkBranch" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="isIns" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="TrackNo" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="VersionNum" Type="System.String" DbType="NVarChar(13)" CanBeNull="true" />
      <Column Name="LangCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BPNameOW" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="BillToOW" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ShipToOW" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="RetInvoice" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ClsDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MInvNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MInvDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SeqCode" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Serial" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SeriesStr" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="SubStr" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="Model" Type="System.String" DbType="NVarChar(6)" CanBeNull="true" />
      <Column Name="TaxOnExp" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="TaxOnExpFc" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="TaxOnExpSc" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="TaxOnExAp" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="TaxOnExApF" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="TaxOnExApS" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="LastPmnTyp" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="LndCstNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UseCorrVat" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="BlkCredMmo" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="OpenForLaC" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Excised" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ExcRefDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ExcRmvTime" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="SrvGpPrcnt" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DepositNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CertNum" Type="System.String" DbType="NVarChar(31)" CanBeNull="true" />
      <Column Name="DutyStatus" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="AutoCrtFlw" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="FlwRefDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FlwRefNum" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="VatJENum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DpmVat" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DpmVatFc" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DpmVatSc" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DpmAppVat" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DpmAppVatF" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DpmAppVatS" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="InsurOp347" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="IgnRelDoc" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="BuildDesc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ResidenNum" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Checker" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Payee" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CopyNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SSIExmpt" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="PQTGrpSer" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PQTGrpNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PQTGrpHW" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ReopOriDoc" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ReopManCls" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DocManClsd" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ClosingOpt" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SpecDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Ordered" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="NTSApprov" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="NTSWebSite" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="NTSeTaxNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NTSApprNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PayDuMonth" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ExtraMonth" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ExtraDays" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CdcOffset" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SignMsg" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SignDigest" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CertifNum" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="KeyVersion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EDocGenTyp" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ESeries" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="EDocNum" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EDocExpFrm" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OnlineQuo" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="POSEqNum" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="POSManufSN" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="POSCashN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EDocStatus" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="EDocCntnt" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="EDocProces" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="EDocErrCod" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EDocErrMsg" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="EDocCancel" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="EDocTest" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="EDocPrefix" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="CUP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CIG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DpmAsDscnt" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Attachment" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="AtcEntry" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SupplCode" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="GTSRlvnt" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="BaseDisc" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="BaseDiscSc" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="BaseDiscFc" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="BaseDiscPr" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="CreateTS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdateTS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SrvTaxRule" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="AnnInvDecR" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Supplier" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Releaser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Receiver" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ToWhsCode" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="AssetDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Requester" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="ReqName" Type="System.String" DbType="NVarChar(155)" CanBeNull="true" />
      <Column Name="Branch" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Department" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Notify" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ReqType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OriginType" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="IsReuseNum" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="IsReuseNFN" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DocDlvry" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="PaidDpm" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="PaidDpmF" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="PaidDpmS" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="EnvTypeNFe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AgrNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsAlt" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="AltBaseTyp" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AltBaseEnt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AuthCode" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="StDlvDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="StDlvTime" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EndDlvDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDlvTime" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VclPlate" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ElCoStatus" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="AtDocType" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="ElCoMsg" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="PrintSEPA" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="FreeChrg" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="FreeChrgFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="FreeChrgSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="NfeValue" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="FiscDocNum" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="RelatedTyp" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RelatedEnt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CCDEntry" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NfePrntFo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ZrdAbs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="POSRcptNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FoCTax" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="FoCTaxFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="FoCTaxSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="TpCusPres" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExcDocDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FoCFrght" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="FoCFrghtFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="FoCFrghtSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="InterimTyp" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="PTICode" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="Letter" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="FolNumFrom" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FolNumTo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FolSeries" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SplitTax" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="SplitTaxFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="SplitTaxSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ToBinCode" Type="System.String" DbType="NVarChar(228)" CanBeNull="true" />
      <Column Name="PriceMode" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="PoDropPrss" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="PermitNo" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="MYFtype" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="DocTaxID" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="DateReport" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RepSection" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="ExclTaxRep" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="PosCashReg" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DmpTransID" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ECommerBP" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="EComerGSTN" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Revision" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="RevRefNo" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="RevRefDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RevCreRefN" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="RevCreRefD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TaxInvNo" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="FrmBpDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GSTTranTyp" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="BaseType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BaseEntry" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ComTrade" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="UseBilAddr" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="IssReason" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ComTradeRt" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="SplitPmnt" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="SOIWizId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SelfPosted" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="EnBnkAcct" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="EncryptIV" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DPPStatus" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="SAPPassprt" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="EWBGenType" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="CtActTax" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="CtActTaxFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="CtActTaxSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="EDocType" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QRCodeSrc" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="AggregDoc" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DataVers" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ShipState" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="ShipPlace" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="CustOffice" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="FCI" Type="System.String" DbType="NVarChar(36)" CanBeNull="true" />
      <Column Name="NnSbCuAmnt" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="NnSbCuSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="NnSbCuFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ExepCuAmnt" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ExepCuSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ExepCuFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="AddLegIn" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="LegTextF" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IndFinal" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DANFELgTxt" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PostPmntWT" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QRCodeSPGn" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="FCEPmnMean" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ReqCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NotRel4MI" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Rel4PPTax" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="U_SELLO" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="U_FECHELABORACION" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="U_HORAINICIO" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="U_HORATERMINO" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="U_INV_0010_SyncStat" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="U_INV_0010_UpdFrom" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="U_FolioRef" Type="System.String" DbType="NVarChar(18)" CanBeNull="true" />
      <Column Name="U_FchRef" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="U_RazonRef" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="U_SN_Transporte" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="U_No_DI" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="U_No_SUI" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="U_CantCamiones" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="U_ETD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="U_ETA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="U_No_Despacho" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="U_No_Ctto_Proform" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="U_FacturaProveedor" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="U_CRT_BL" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="U_Ind_PackList" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="U_No_PagoTesorero" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="U_Ind_CertifAnalisis" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="U_Ind_CertifSeguro" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="U_Ind_CertifOrigen" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="U_Ind_CertifCalidad" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="U_Ind_CertifLote" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="U_Ind_CertifSalud" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="U_Ind_EnvDoctosAga" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="U_FechaEnvioAGA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="U_PagoProvMerc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="U_PagoProvFlete" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="U_ValorDescarga" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="U_PagoProvFleteNac" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="U_SelloAduana" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="U_SelloSAG" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="U_IdWms" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="U_UsuarioWms" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="U_No_Contenedor" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="U_No_DI_Despacho" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="U_TipoDescarga" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="U_TipoContenedor" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="U_TipoEntidad" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="U_FolioEntidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="U_PATENTECAMION" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="U_TpoDocRef" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="U_CodRef" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="U_IndTraslado" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="U_TipoDesp" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="U_PuertoSalida" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="U_PuertoLlegada" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="U_Folio_Guia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="U_NumAgenda" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="U_Hora_entrega" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="U_IndVuelta" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="U_IndPasaWMS" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="U_TipoRecibo" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="U_PaisOrigenMP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="U_Bol_Ini" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="U_Bol_Fin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="U_NUMFACT" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="U_IndFacturado" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="U_HoraEnvioAGA" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="U_ItemCod_Ref" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="U_Areas" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="U_ErrorDte" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="U_Traspaso_FE" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="U_NXSucursales" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="U_ModVenta" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="U_ClauVenta" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="U_Transporte" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="U_PtoDesemb" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="U_PtoEmbarque" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="U_NX_PESOBRUTO" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="U_NX_PESONETO" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="U_NX_BULTOS" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="U_NX_Observacion" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="U_NX_FormaPago" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="U_OtrosDocRef" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="U_NX_CodTpoBultos" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="U_NX_CantBultos" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="U_NX_Marcas" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="U_NX_IdContainer" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="U_NX_Sello" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="U_NX_EmisorSello" Type="System.String" DbType="NVarChar(70)" CanBeNull="true" />
      <Column Name="U_IndPrecioEntrega" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="U_IdInventario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="U_TipoAjuste" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="U_Excluir" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="U_Factoring" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="U_CodFact" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="U_newduedate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="U_Comment" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="U_BLdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="U_IndDoctoPagable" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="U_IndOfertaSel" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="U_ValorTransporte" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="U_ValorSeguro" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="U_TipoCambioAdu" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="U_Agendamiento" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="U_NCamion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="U_Nave" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="U_Contenedores" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="U_SN_Asociado" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="U_NChofer" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="U_HoraIncioCaDe" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="U_HoraTerminoCaDe" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="U_TpoDocOtRef" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="U_FolioOtRef" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="U_FechaOtRef" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="U_RznRefOtref" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="U_Pais_destin" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="U_UrlPdf1" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="U_UrlPdf2" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="U_ApprovalStatus" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="U_rutFactoring" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="U_fechaCesion" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="U_fechaFactura" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="U_fechaVencimiento" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="U_glosa" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="U_montoCedido" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="U_ApprovalDate" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="U_NCertificadoSeg" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_CVT_ListaClientes_GetClientes" Member="VW_CVT_ListaClientes_GetClientes">
    <Type Name="VW_CVT_ListaClientes_GetClientes">
      <Column Name="FechaActualizacion" Type="System.String" DbType="VarChar(59)" CanBeNull="true" />
      <Column Name="Rut" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="Cod_Interno" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Razon_Social" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="E_Mail" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_CVT_ListaProductos_GetProductos" Member="VW_CVT_ListaProductos_GetProductos">
    <Type Name="VW_CVT_ListaProductos_GetProductos">
      <Column Name="FechaActualizacion" Type="System.String" DbType="VarChar(59)" CanBeNull="true" />
      <Column Name="Erp" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="BarCode" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Categoria" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SubCategoria" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Formato" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TipoFormato" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CantidadxUM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Activado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CodProveedor" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Proveedor" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_CVT_ListaSucursales_GetSucursales" Member="VW_CVT_ListaSucursales_GetSucursales">
    <Type Name="VW_CVT_ListaSucursales_GetSucursales">
      <Column Name="Tipo" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Cod_Cliente" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Cod_Interno" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EAN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Direccion" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Ciudad" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Comuna" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>