#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBTest
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ZBO_MMETRO")]
	public partial class DBMLSapSMMDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertMMETRO_CRD1(MMETRO_CRD1 instance);
    partial void UpdateMMETRO_CRD1(MMETRO_CRD1 instance);
    partial void DeleteMMETRO_CRD1(MMETRO_CRD1 instance);
    #endregion
		
		public DBMLSapSMMDataContext() : 
				base(global::DBTest.Properties.Settings.Default.ZBO_MMETROConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DBMLSapSMMDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBMLSapSMMDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBMLSapSMMDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBMLSapSMMDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<VW_SMM_STOCK> VW_SMM_STOCK
		{
			get
			{
				return this.GetTable<VW_SMM_STOCK>();
			}
		}
		
		public System.Data.Linq.Table<VW_SMM_ListadoPrecios_Distribucion_API> VW_SMM_ListadoPrecios_Distribucion_API
		{
			get
			{
				return this.GetTable<VW_SMM_ListadoPrecios_Distribucion_API>();
			}
		}
		
		public System.Data.Linq.Table<VW_SMM_ListadoPrecios_API> VW_SMM_ListadoPrecios_API
		{
			get
			{
				return this.GetTable<VW_SMM_ListadoPrecios_API>();
			}
		}
		
		public System.Data.Linq.Table<MMETRO_CRD1> MMETRO_CRD1
		{
			get
			{
				return this.GetTable<MMETRO_CRD1>();
			}
		}
		
		public System.Data.Linq.Table<VW_SMM_ListaClientes_GetClientes> VW_SMM_ListaClientes_GetClientes
		{
			get
			{
				return this.GetTable<VW_SMM_ListaClientes_GetClientes>();
			}
		}
		
		public System.Data.Linq.Table<VW_SMM_ListaProductos_GetProductos> VW_SMM_ListaProductos_GetProductos
		{
			get
			{
				return this.GetTable<VW_SMM_ListaProductos_GetProductos>();
			}
		}
		
		public System.Data.Linq.Table<VW_SMM_ListaSucursales_GetSucursales> VW_SMM_ListaSucursales_GetSucursales
		{
			get
			{
				return this.GetTable<VW_SMM_ListaSucursales_GetSucursales>();
			}
		}
		
		public System.Data.Linq.Table<VW_SMM_ListadoPrecios_Unidades_API> VW_SMM_ListadoPrecios_Unidades_API
		{
			get
			{
				return this.GetTable<VW_SMM_ListadoPrecios_Unidades_API>();
			}
		}
		
		public System.Data.Linq.Table<VW_SMM_ListaProductos_Unidades_GetProductos> VW_SMM_ListaProductos_Unidades_GetProductos
		{
			get
			{
				return this.GetTable<VW_SMM_ListaProductos_Unidades_GetProductos>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_SMM_STOCK")]
	public partial class VW_SMM_STOCK
	{
		
		private string _itemcode;
		
		private System.Nullable<int> _Stock;
		
		private int _UomEntry;
		
		private string _UomCode;
		
		private string _BcdCode;
		
		public VW_SMM_STOCK()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_itemcode", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string itemcode
		{
			get
			{
				return this._itemcode;
			}
			set
			{
				if ((this._itemcode != value))
				{
					this._itemcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stock", DbType="Int")]
		public System.Nullable<int> Stock
		{
			get
			{
				return this._Stock;
			}
			set
			{
				if ((this._Stock != value))
				{
					this._Stock = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UomEntry", DbType="Int NOT NULL")]
		public int UomEntry
		{
			get
			{
				return this._UomEntry;
			}
			set
			{
				if ((this._UomEntry != value))
				{
					this._UomEntry = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UomCode", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string UomCode
		{
			get
			{
				return this._UomCode;
			}
			set
			{
				if ((this._UomCode != value))
				{
					this._UomCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BcdCode", DbType="NVarChar(254) NOT NULL", CanBeNull=false)]
		public string BcdCode
		{
			get
			{
				return this._BcdCode;
			}
			set
			{
				if ((this._BcdCode != value))
				{
					this._BcdCode = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_SMM_ListadoPrecios_Distribucion_API")]
	public partial class VW_SMM_ListadoPrecios_Distribucion_API
	{
		
		private string _Und_Medida;
		
		private System.Nullable<int> _Cantidad_x_UPC;
		
		private System.Nullable<int> _UomEntry;
		
		private string _CodProducto;
		
		private string _Producto;
		
		private System.Nullable<int> _Price;
		
		private string _Impuesto;
		
		private System.Nullable<int> _Rate;
		
		private System.Nullable<int> _Neto;
		
		private string _BcdCode;
		
		public VW_SMM_ListadoPrecios_Distribucion_API()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Und Medida]", Storage="_Und_Medida", DbType="NVarChar(20)")]
		public string Und_Medida
		{
			get
			{
				return this._Und_Medida;
			}
			set
			{
				if ((this._Und_Medida != value))
				{
					this._Und_Medida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Cantidad x UPC]", Storage="_Cantidad_x_UPC", DbType="Int")]
		public System.Nullable<int> Cantidad_x_UPC
		{
			get
			{
				return this._Cantidad_x_UPC;
			}
			set
			{
				if ((this._Cantidad_x_UPC != value))
				{
					this._Cantidad_x_UPC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UomEntry", DbType="Int")]
		public System.Nullable<int> UomEntry
		{
			get
			{
				return this._UomEntry;
			}
			set
			{
				if ((this._UomEntry != value))
				{
					this._UomEntry = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodProducto", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CodProducto
		{
			get
			{
				return this._CodProducto;
			}
			set
			{
				if ((this._CodProducto != value))
				{
					this._CodProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Producto", DbType="NVarChar(100)")]
		public string Producto
		{
			get
			{
				return this._Producto;
			}
			set
			{
				if ((this._Producto != value))
				{
					this._Producto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Int")]
		public System.Nullable<int> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Impuesto", DbType="NVarChar(8)")]
		public string Impuesto
		{
			get
			{
				return this._Impuesto;
			}
			set
			{
				if ((this._Impuesto != value))
				{
					this._Impuesto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rate", DbType="Int")]
		public System.Nullable<int> Rate
		{
			get
			{
				return this._Rate;
			}
			set
			{
				if ((this._Rate != value))
				{
					this._Rate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Neto", DbType="Int")]
		public System.Nullable<int> Neto
		{
			get
			{
				return this._Neto;
			}
			set
			{
				if ((this._Neto != value))
				{
					this._Neto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BcdCode", DbType="NVarChar(254)")]
		public string BcdCode
		{
			get
			{
				return this._BcdCode;
			}
			set
			{
				if ((this._BcdCode != value))
				{
					this._BcdCode = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_SMM_ListadoPrecios_API")]
	public partial class VW_SMM_ListadoPrecios_API
	{
		
		private string _Und_Medida;
		
		private System.Nullable<int> _Cantidad_x_UPC;
		
		private System.Nullable<int> _UomEntry;
		
		private string _CodProducto;
		
		private string _Producto;
		
		private System.Nullable<int> _Price;
		
		private string _Impuesto;
		
		private System.Nullable<int> _Rate;
		
		private System.Nullable<int> _Neto;
		
		private string _BcdCode;
		
		public VW_SMM_ListadoPrecios_API()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Und Medida]", Storage="_Und_Medida", DbType="NVarChar(20)")]
		public string Und_Medida
		{
			get
			{
				return this._Und_Medida;
			}
			set
			{
				if ((this._Und_Medida != value))
				{
					this._Und_Medida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Cantidad x UPC]", Storage="_Cantidad_x_UPC", DbType="Int")]
		public System.Nullable<int> Cantidad_x_UPC
		{
			get
			{
				return this._Cantidad_x_UPC;
			}
			set
			{
				if ((this._Cantidad_x_UPC != value))
				{
					this._Cantidad_x_UPC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UomEntry", DbType="Int")]
		public System.Nullable<int> UomEntry
		{
			get
			{
				return this._UomEntry;
			}
			set
			{
				if ((this._UomEntry != value))
				{
					this._UomEntry = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodProducto", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CodProducto
		{
			get
			{
				return this._CodProducto;
			}
			set
			{
				if ((this._CodProducto != value))
				{
					this._CodProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Producto", DbType="NVarChar(100)")]
		public string Producto
		{
			get
			{
				return this._Producto;
			}
			set
			{
				if ((this._Producto != value))
				{
					this._Producto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Int")]
		public System.Nullable<int> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Impuesto", DbType="NVarChar(8)")]
		public string Impuesto
		{
			get
			{
				return this._Impuesto;
			}
			set
			{
				if ((this._Impuesto != value))
				{
					this._Impuesto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rate", DbType="Int")]
		public System.Nullable<int> Rate
		{
			get
			{
				return this._Rate;
			}
			set
			{
				if ((this._Rate != value))
				{
					this._Rate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Neto", DbType="Int")]
		public System.Nullable<int> Neto
		{
			get
			{
				return this._Neto;
			}
			set
			{
				if ((this._Neto != value))
				{
					this._Neto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BcdCode", DbType="NVarChar(254)")]
		public string BcdCode
		{
			get
			{
				return this._BcdCode;
			}
			set
			{
				if ((this._BcdCode != value))
				{
					this._BcdCode = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CRD1")]
	public partial class MMETRO_CRD1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Address;
		
		private string _CardCode;
		
		private string _Street;
		
		private string _Block;
		
		private string _ZipCode;
		
		private string _City;
		
		private string _County;
		
		private string _Country;
		
		private string _State;
		
		private System.Nullable<short> _UserSign;
		
		private System.Nullable<int> _LogInstanc;
		
		private string _ObjType;
		
		private string _LicTradNum;
		
		private System.Nullable<int> _LineNum;
		
		private string _TaxCode;
		
		private string _Building;
		
		private char _AdresType;
		
		private string _Address2;
		
		private string _Address3;
		
		private string _AddrType;
		
		private string _StreetNo;
		
		private string _AltCrdName;
		
		private string _AltTaxId;
		
		private string _TaxOffice;
		
		private string _GlblLocNum;
		
		private string _Ntnlty;
		
		private string _DIOTNat;
		
		private System.Nullable<char> _TaaSEnbl;
		
		private string _GSTRegnNo;
		
		private System.Nullable<int> _GSTType;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<int> _CreateTS;
		
		private string _EncryptIV;
		
		private string _MYFType;
		
		private System.Nullable<System.DateTime> _VatResDate;
		
		private System.Nullable<int> _VatResCode;
		
		private string _VatResName;
		
		private string _VatResAddr;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnCardCodeChanging(string value);
    partial void OnCardCodeChanged();
    partial void OnStreetChanging(string value);
    partial void OnStreetChanged();
    partial void OnBlockChanging(string value);
    partial void OnBlockChanged();
    partial void OnZipCodeChanging(string value);
    partial void OnZipCodeChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnCountyChanging(string value);
    partial void OnCountyChanged();
    partial void OnCountryChanging(string value);
    partial void OnCountryChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnUserSignChanging(System.Nullable<short> value);
    partial void OnUserSignChanged();
    partial void OnLogInstancChanging(System.Nullable<int> value);
    partial void OnLogInstancChanged();
    partial void OnObjTypeChanging(string value);
    partial void OnObjTypeChanged();
    partial void OnLicTradNumChanging(string value);
    partial void OnLicTradNumChanged();
    partial void OnLineNumChanging(System.Nullable<int> value);
    partial void OnLineNumChanged();
    partial void OnTaxCodeChanging(string value);
    partial void OnTaxCodeChanged();
    partial void OnBuildingChanging(string value);
    partial void OnBuildingChanged();
    partial void OnAdresTypeChanging(char value);
    partial void OnAdresTypeChanged();
    partial void OnAddress2Changing(string value);
    partial void OnAddress2Changed();
    partial void OnAddress3Changing(string value);
    partial void OnAddress3Changed();
    partial void OnAddrTypeChanging(string value);
    partial void OnAddrTypeChanged();
    partial void OnStreetNoChanging(string value);
    partial void OnStreetNoChanged();
    partial void OnAltCrdNameChanging(string value);
    partial void OnAltCrdNameChanged();
    partial void OnAltTaxIdChanging(string value);
    partial void OnAltTaxIdChanged();
    partial void OnTaxOfficeChanging(string value);
    partial void OnTaxOfficeChanged();
    partial void OnGlblLocNumChanging(string value);
    partial void OnGlblLocNumChanged();
    partial void OnNtnltyChanging(string value);
    partial void OnNtnltyChanged();
    partial void OnDIOTNatChanging(string value);
    partial void OnDIOTNatChanged();
    partial void OnTaaSEnblChanging(System.Nullable<char> value);
    partial void OnTaaSEnblChanged();
    partial void OnGSTRegnNoChanging(string value);
    partial void OnGSTRegnNoChanged();
    partial void OnGSTTypeChanging(System.Nullable<int> value);
    partial void OnGSTTypeChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnCreateTSChanging(System.Nullable<int> value);
    partial void OnCreateTSChanged();
    partial void OnEncryptIVChanging(string value);
    partial void OnEncryptIVChanged();
    partial void OnMYFTypeChanging(string value);
    partial void OnMYFTypeChanged();
    partial void OnVatResDateChanging(System.Nullable<System.DateTime> value);
    partial void OnVatResDateChanged();
    partial void OnVatResCodeChanging(System.Nullable<int> value);
    partial void OnVatResCodeChanged();
    partial void OnVatResNameChanging(string value);
    partial void OnVatResNameChanged();
    partial void OnVatResAddrChanging(string value);
    partial void OnVatResAddrChanged();
    #endregion
		
		public MMETRO_CRD1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardCode", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CardCode
		{
			get
			{
				return this._CardCode;
			}
			set
			{
				if ((this._CardCode != value))
				{
					this.OnCardCodeChanging(value);
					this.SendPropertyChanging();
					this._CardCode = value;
					this.SendPropertyChanged("CardCode");
					this.OnCardCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Street", DbType="NVarChar(100)")]
		public string Street
		{
			get
			{
				return this._Street;
			}
			set
			{
				if ((this._Street != value))
				{
					this.OnStreetChanging(value);
					this.SendPropertyChanging();
					this._Street = value;
					this.SendPropertyChanged("Street");
					this.OnStreetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Block", DbType="NVarChar(100)")]
		public string Block
		{
			get
			{
				return this._Block;
			}
			set
			{
				if ((this._Block != value))
				{
					this.OnBlockChanging(value);
					this.SendPropertyChanging();
					this._Block = value;
					this.SendPropertyChanged("Block");
					this.OnBlockChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZipCode", DbType="NVarChar(20)")]
		public string ZipCode
		{
			get
			{
				return this._ZipCode;
			}
			set
			{
				if ((this._ZipCode != value))
				{
					this.OnZipCodeChanging(value);
					this.SendPropertyChanging();
					this._ZipCode = value;
					this.SendPropertyChanged("ZipCode");
					this.OnZipCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(100)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_County", DbType="NVarChar(100)")]
		public string County
		{
			get
			{
				return this._County;
			}
			set
			{
				if ((this._County != value))
				{
					this.OnCountyChanging(value);
					this.SendPropertyChanging();
					this._County = value;
					this.SendPropertyChanged("County");
					this.OnCountyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="NVarChar(3)")]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this.OnCountryChanging(value);
					this.SendPropertyChanging();
					this._Country = value;
					this.SendPropertyChanged("Country");
					this.OnCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="NVarChar(3)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserSign", DbType="SmallInt")]
		public System.Nullable<short> UserSign
		{
			get
			{
				return this._UserSign;
			}
			set
			{
				if ((this._UserSign != value))
				{
					this.OnUserSignChanging(value);
					this.SendPropertyChanging();
					this._UserSign = value;
					this.SendPropertyChanged("UserSign");
					this.OnUserSignChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogInstanc", DbType="Int")]
		public System.Nullable<int> LogInstanc
		{
			get
			{
				return this._LogInstanc;
			}
			set
			{
				if ((this._LogInstanc != value))
				{
					this.OnLogInstancChanging(value);
					this.SendPropertyChanging();
					this._LogInstanc = value;
					this.SendPropertyChanged("LogInstanc");
					this.OnLogInstancChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ObjType", DbType="NVarChar(20)")]
		public string ObjType
		{
			get
			{
				return this._ObjType;
			}
			set
			{
				if ((this._ObjType != value))
				{
					this.OnObjTypeChanging(value);
					this.SendPropertyChanging();
					this._ObjType = value;
					this.SendPropertyChanged("ObjType");
					this.OnObjTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LicTradNum", DbType="NVarChar(32)")]
		public string LicTradNum
		{
			get
			{
				return this._LicTradNum;
			}
			set
			{
				if ((this._LicTradNum != value))
				{
					this.OnLicTradNumChanging(value);
					this.SendPropertyChanging();
					this._LicTradNum = value;
					this.SendPropertyChanged("LicTradNum");
					this.OnLicTradNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LineNum", DbType="Int")]
		public System.Nullable<int> LineNum
		{
			get
			{
				return this._LineNum;
			}
			set
			{
				if ((this._LineNum != value))
				{
					this.OnLineNumChanging(value);
					this.SendPropertyChanging();
					this._LineNum = value;
					this.SendPropertyChanged("LineNum");
					this.OnLineNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxCode", DbType="NVarChar(8)")]
		public string TaxCode
		{
			get
			{
				return this._TaxCode;
			}
			set
			{
				if ((this._TaxCode != value))
				{
					this.OnTaxCodeChanging(value);
					this.SendPropertyChanging();
					this._TaxCode = value;
					this.SendPropertyChanged("TaxCode");
					this.OnTaxCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Building", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Building
		{
			get
			{
				return this._Building;
			}
			set
			{
				if ((this._Building != value))
				{
					this.OnBuildingChanging(value);
					this.SendPropertyChanging();
					this._Building = value;
					this.SendPropertyChanged("Building");
					this.OnBuildingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdresType", DbType="Char(1) NOT NULL", IsPrimaryKey=true)]
		public char AdresType
		{
			get
			{
				return this._AdresType;
			}
			set
			{
				if ((this._AdresType != value))
				{
					this.OnAdresTypeChanging(value);
					this.SendPropertyChanging();
					this._AdresType = value;
					this.SendPropertyChanged("AdresType");
					this.OnAdresTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address2", DbType="NVarChar(50)")]
		public string Address2
		{
			get
			{
				return this._Address2;
			}
			set
			{
				if ((this._Address2 != value))
				{
					this.OnAddress2Changing(value);
					this.SendPropertyChanging();
					this._Address2 = value;
					this.SendPropertyChanged("Address2");
					this.OnAddress2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address3", DbType="NVarChar(50)")]
		public string Address3
		{
			get
			{
				return this._Address3;
			}
			set
			{
				if ((this._Address3 != value))
				{
					this.OnAddress3Changing(value);
					this.SendPropertyChanging();
					this._Address3 = value;
					this.SendPropertyChanged("Address3");
					this.OnAddress3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddrType", DbType="NVarChar(100)")]
		public string AddrType
		{
			get
			{
				return this._AddrType;
			}
			set
			{
				if ((this._AddrType != value))
				{
					this.OnAddrTypeChanging(value);
					this.SendPropertyChanging();
					this._AddrType = value;
					this.SendPropertyChanged("AddrType");
					this.OnAddrTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StreetNo", DbType="NVarChar(100)")]
		public string StreetNo
		{
			get
			{
				return this._StreetNo;
			}
			set
			{
				if ((this._StreetNo != value))
				{
					this.OnStreetNoChanging(value);
					this.SendPropertyChanging();
					this._StreetNo = value;
					this.SendPropertyChanged("StreetNo");
					this.OnStreetNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AltCrdName", DbType="NVarChar(100)")]
		public string AltCrdName
		{
			get
			{
				return this._AltCrdName;
			}
			set
			{
				if ((this._AltCrdName != value))
				{
					this.OnAltCrdNameChanging(value);
					this.SendPropertyChanging();
					this._AltCrdName = value;
					this.SendPropertyChanged("AltCrdName");
					this.OnAltCrdNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AltTaxId", DbType="NVarChar(32)")]
		public string AltTaxId
		{
			get
			{
				return this._AltTaxId;
			}
			set
			{
				if ((this._AltTaxId != value))
				{
					this.OnAltTaxIdChanging(value);
					this.SendPropertyChanging();
					this._AltTaxId = value;
					this.SendPropertyChanged("AltTaxId");
					this.OnAltTaxIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxOffice", DbType="NVarChar(50)")]
		public string TaxOffice
		{
			get
			{
				return this._TaxOffice;
			}
			set
			{
				if ((this._TaxOffice != value))
				{
					this.OnTaxOfficeChanging(value);
					this.SendPropertyChanging();
					this._TaxOffice = value;
					this.SendPropertyChanged("TaxOffice");
					this.OnTaxOfficeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GlblLocNum", DbType="NVarChar(50)")]
		public string GlblLocNum
		{
			get
			{
				return this._GlblLocNum;
			}
			set
			{
				if ((this._GlblLocNum != value))
				{
					this.OnGlblLocNumChanging(value);
					this.SendPropertyChanging();
					this._GlblLocNum = value;
					this.SendPropertyChanged("GlblLocNum");
					this.OnGlblLocNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ntnlty", DbType="NVarChar(100)")]
		public string Ntnlty
		{
			get
			{
				return this._Ntnlty;
			}
			set
			{
				if ((this._Ntnlty != value))
				{
					this.OnNtnltyChanging(value);
					this.SendPropertyChanging();
					this._Ntnlty = value;
					this.SendPropertyChanged("Ntnlty");
					this.OnNtnltyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIOTNat", DbType="NVarChar(3)")]
		public string DIOTNat
		{
			get
			{
				return this._DIOTNat;
			}
			set
			{
				if ((this._DIOTNat != value))
				{
					this.OnDIOTNatChanging(value);
					this.SendPropertyChanging();
					this._DIOTNat = value;
					this.SendPropertyChanged("DIOTNat");
					this.OnDIOTNatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaaSEnbl", DbType="Char(1)")]
		public System.Nullable<char> TaaSEnbl
		{
			get
			{
				return this._TaaSEnbl;
			}
			set
			{
				if ((this._TaaSEnbl != value))
				{
					this.OnTaaSEnblChanging(value);
					this.SendPropertyChanging();
					this._TaaSEnbl = value;
					this.SendPropertyChanged("TaaSEnbl");
					this.OnTaaSEnblChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GSTRegnNo", DbType="NVarChar(15)")]
		public string GSTRegnNo
		{
			get
			{
				return this._GSTRegnNo;
			}
			set
			{
				if ((this._GSTRegnNo != value))
				{
					this.OnGSTRegnNoChanging(value);
					this.SendPropertyChanging();
					this._GSTRegnNo = value;
					this.SendPropertyChanged("GSTRegnNo");
					this.OnGSTRegnNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GSTType", DbType="Int")]
		public System.Nullable<int> GSTType
		{
			get
			{
				return this._GSTType;
			}
			set
			{
				if ((this._GSTType != value))
				{
					this.OnGSTTypeChanging(value);
					this.SendPropertyChanging();
					this._GSTType = value;
					this.SendPropertyChanged("GSTType");
					this.OnGSTTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateTS", DbType="Int")]
		public System.Nullable<int> CreateTS
		{
			get
			{
				return this._CreateTS;
			}
			set
			{
				if ((this._CreateTS != value))
				{
					this.OnCreateTSChanging(value);
					this.SendPropertyChanging();
					this._CreateTS = value;
					this.SendPropertyChanged("CreateTS");
					this.OnCreateTSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EncryptIV", DbType="NVarChar(100)")]
		public string EncryptIV
		{
			get
			{
				return this._EncryptIV;
			}
			set
			{
				if ((this._EncryptIV != value))
				{
					this.OnEncryptIVChanging(value);
					this.SendPropertyChanging();
					this._EncryptIV = value;
					this.SendPropertyChanged("EncryptIV");
					this.OnEncryptIVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MYFType", DbType="NVarChar(2)")]
		public string MYFType
		{
			get
			{
				return this._MYFType;
			}
			set
			{
				if ((this._MYFType != value))
				{
					this.OnMYFTypeChanging(value);
					this.SendPropertyChanging();
					this._MYFType = value;
					this.SendPropertyChanged("MYFType");
					this.OnMYFTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VatResDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> VatResDate
		{
			get
			{
				return this._VatResDate;
			}
			set
			{
				if ((this._VatResDate != value))
				{
					this.OnVatResDateChanging(value);
					this.SendPropertyChanging();
					this._VatResDate = value;
					this.SendPropertyChanged("VatResDate");
					this.OnVatResDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VatResCode", DbType="Int")]
		public System.Nullable<int> VatResCode
		{
			get
			{
				return this._VatResCode;
			}
			set
			{
				if ((this._VatResCode != value))
				{
					this.OnVatResCodeChanging(value);
					this.SendPropertyChanging();
					this._VatResCode = value;
					this.SendPropertyChanged("VatResCode");
					this.OnVatResCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VatResName", DbType="NVarChar(254)")]
		public string VatResName
		{
			get
			{
				return this._VatResName;
			}
			set
			{
				if ((this._VatResName != value))
				{
					this.OnVatResNameChanging(value);
					this.SendPropertyChanging();
					this._VatResName = value;
					this.SendPropertyChanged("VatResName");
					this.OnVatResNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VatResAddr", DbType="NVarChar(254)")]
		public string VatResAddr
		{
			get
			{
				return this._VatResAddr;
			}
			set
			{
				if ((this._VatResAddr != value))
				{
					this.OnVatResAddrChanging(value);
					this.SendPropertyChanging();
					this._VatResAddr = value;
					this.SendPropertyChanged("VatResAddr");
					this.OnVatResAddrChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_SMM_ListaClientes_GetClientes")]
	public partial class VW_SMM_ListaClientes_GetClientes
	{
		
		private string _FechaActualizacion;
		
		private string _Rut;
		
		private string _Cod_Interno;
		
		private string _Razon_Social;
		
		private string _E_Mail;
		
		private string _Telefono;
		
		private string _Condicion_Pago;
		
		private System.Nullable<decimal> _Linea_Credito;
		
		private System.Nullable<int> _SlpCode;
		
		private string _Vendedor;
		
		public VW_SMM_ListaClientes_GetClientes()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaActualizacion", DbType="VarChar(59)")]
		public string FechaActualizacion
		{
			get
			{
				return this._FechaActualizacion;
			}
			set
			{
				if ((this._FechaActualizacion != value))
				{
					this._FechaActualizacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rut", DbType="NVarChar(32)")]
		public string Rut
		{
			get
			{
				return this._Rut;
			}
			set
			{
				if ((this._Rut != value))
				{
					this._Rut = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod_Interno", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string Cod_Interno
		{
			get
			{
				return this._Cod_Interno;
			}
			set
			{
				if ((this._Cod_Interno != value))
				{
					this._Cod_Interno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Razon_Social", DbType="NVarChar(100)")]
		public string Razon_Social
		{
			get
			{
				return this._Razon_Social;
			}
			set
			{
				if ((this._Razon_Social != value))
				{
					this._Razon_Social = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_Mail", DbType="NVarChar(100)")]
		public string E_Mail
		{
			get
			{
				return this._E_Mail;
			}
			set
			{
				if ((this._E_Mail != value))
				{
					this._E_Mail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="NVarChar(50)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Condicion_Pago", DbType="NVarChar(100)")]
		public string Condicion_Pago
		{
			get
			{
				return this._Condicion_Pago;
			}
			set
			{
				if ((this._Condicion_Pago != value))
				{
					this._Condicion_Pago = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Linea_Credito", DbType="Decimal(19,6)")]
		public System.Nullable<decimal> Linea_Credito
		{
			get
			{
				return this._Linea_Credito;
			}
			set
			{
				if ((this._Linea_Credito != value))
				{
					this._Linea_Credito = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SlpCode", DbType="Int")]
		public System.Nullable<int> SlpCode
		{
			get
			{
				return this._SlpCode;
			}
			set
			{
				if ((this._SlpCode != value))
				{
					this._SlpCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vendedor", DbType="NVarChar(155)")]
		public string Vendedor
		{
			get
			{
				return this._Vendedor;
			}
			set
			{
				if ((this._Vendedor != value))
				{
					this._Vendedor = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_SMM_ListaProductos_GetProductos")]
	public partial class VW_SMM_ListaProductos_GetProductos
	{
		
		private string _FechaActualizacion;
		
		private string _ItemCode;
		
		private string _ItemName;
		
		private string _BcdCode;
		
		private string _UomCode;
		
		private System.Nullable<int> _UomEntry;
		
		private System.Nullable<int> _CantidadxUM;
		
		private string _Marca;
		
		private string _Categoria;
		
		private string _SubCategoria;
		
		private string _CodProveedor;
		
		private string _Proveedor;
		
		private System.Nullable<int> _U_Multiplo;
		
		private System.Nullable<int> _U_VentaMinima;
		
		public VW_SMM_ListaProductos_GetProductos()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaActualizacion", DbType="VarChar(59)")]
		public string FechaActualizacion
		{
			get
			{
				return this._FechaActualizacion;
			}
			set
			{
				if ((this._FechaActualizacion != value))
				{
					this._FechaActualizacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ItemCode
		{
			get
			{
				return this._ItemCode;
			}
			set
			{
				if ((this._ItemCode != value))
				{
					this._ItemCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemName", DbType="NVarChar(200)")]
		public string ItemName
		{
			get
			{
				return this._ItemName;
			}
			set
			{
				if ((this._ItemName != value))
				{
					this._ItemName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BcdCode", DbType="NVarChar(254)")]
		public string BcdCode
		{
			get
			{
				return this._BcdCode;
			}
			set
			{
				if ((this._BcdCode != value))
				{
					this._BcdCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UomCode", DbType="NVarChar(20)")]
		public string UomCode
		{
			get
			{
				return this._UomCode;
			}
			set
			{
				if ((this._UomCode != value))
				{
					this._UomCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UomEntry", DbType="Int")]
		public System.Nullable<int> UomEntry
		{
			get
			{
				return this._UomEntry;
			}
			set
			{
				if ((this._UomEntry != value))
				{
					this._UomEntry = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantidadxUM", DbType="Int")]
		public System.Nullable<int> CantidadxUM
		{
			get
			{
				return this._CantidadxUM;
			}
			set
			{
				if ((this._CantidadxUM != value))
				{
					this._CantidadxUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marca", DbType="NVarChar(50)")]
		public string Marca
		{
			get
			{
				return this._Marca;
			}
			set
			{
				if ((this._Marca != value))
				{
					this._Marca = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="NVarChar(100)")]
		public string Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this._Categoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubCategoria", DbType="NVarChar(100)")]
		public string SubCategoria
		{
			get
			{
				return this._SubCategoria;
			}
			set
			{
				if ((this._SubCategoria != value))
				{
					this._SubCategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodProveedor", DbType="NVarChar(15)")]
		public string CodProveedor
		{
			get
			{
				return this._CodProveedor;
			}
			set
			{
				if ((this._CodProveedor != value))
				{
					this._CodProveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Proveedor", DbType="NVarChar(100)")]
		public string Proveedor
		{
			get
			{
				return this._Proveedor;
			}
			set
			{
				if ((this._Proveedor != value))
				{
					this._Proveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_Multiplo", DbType="Int")]
		public System.Nullable<int> U_Multiplo
		{
			get
			{
				return this._U_Multiplo;
			}
			set
			{
				if ((this._U_Multiplo != value))
				{
					this._U_Multiplo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_VentaMinima", DbType="Int")]
		public System.Nullable<int> U_VentaMinima
		{
			get
			{
				return this._U_VentaMinima;
			}
			set
			{
				if ((this._U_VentaMinima != value))
				{
					this._U_VentaMinima = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_SMM_ListaSucursales_GetSucursales")]
	public partial class VW_SMM_ListaSucursales_GetSucursales
	{
		
		private string _FechaActualizacion;
		
		private string _Cod_Cliente;
		
		private string _Cod_Interno;
		
		private string _EAN;
		
		private string _Nombre;
		
		private string _Direccion;
		
		private string _Ciudad;
		
		private string _Comuna;
		
		public VW_SMM_ListaSucursales_GetSucursales()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaActualizacion", DbType="VarChar(59)")]
		public string FechaActualizacion
		{
			get
			{
				return this._FechaActualizacion;
			}
			set
			{
				if ((this._FechaActualizacion != value))
				{
					this._FechaActualizacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod_Cliente", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string Cod_Cliente
		{
			get
			{
				return this._Cod_Cliente;
			}
			set
			{
				if ((this._Cod_Cliente != value))
				{
					this._Cod_Cliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod_Interno", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Cod_Interno
		{
			get
			{
				return this._Cod_Interno;
			}
			set
			{
				if ((this._Cod_Interno != value))
				{
					this._Cod_Interno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EAN", DbType="NVarChar(50)")]
		public string EAN
		{
			get
			{
				return this._EAN;
			}
			set
			{
				if ((this._EAN != value))
				{
					this._EAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="NVarChar(100)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ciudad", DbType="NVarChar(100)")]
		public string Ciudad
		{
			get
			{
				return this._Ciudad;
			}
			set
			{
				if ((this._Ciudad != value))
				{
					this._Ciudad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comuna", DbType="NVarChar(100)")]
		public string Comuna
		{
			get
			{
				return this._Comuna;
			}
			set
			{
				if ((this._Comuna != value))
				{
					this._Comuna = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_SMM_ListadoPrecios_Unidades_API")]
	public partial class VW_SMM_ListadoPrecios_Unidades_API
	{
		
		private string _Und_Medida;
		
		private System.Nullable<int> _Cantidad_x_UPC;
		
		private int _UomEntry;
		
		private string _CodProducto;
		
		private string _Producto;
		
		private System.Nullable<int> _Price;
		
		private string _Impuesto;
		
		private System.Nullable<int> _Rate;
		
		private System.Nullable<int> _Neto;
		
		private string _BcdCode;
		
		public VW_SMM_ListadoPrecios_Unidades_API()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Und Medida]", Storage="_Und_Medida", DbType="NVarChar(20)")]
		public string Und_Medida
		{
			get
			{
				return this._Und_Medida;
			}
			set
			{
				if ((this._Und_Medida != value))
				{
					this._Und_Medida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Cantidad x UPC]", Storage="_Cantidad_x_UPC", DbType="Int")]
		public System.Nullable<int> Cantidad_x_UPC
		{
			get
			{
				return this._Cantidad_x_UPC;
			}
			set
			{
				if ((this._Cantidad_x_UPC != value))
				{
					this._Cantidad_x_UPC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UomEntry", DbType="Int NOT NULL")]
		public int UomEntry
		{
			get
			{
				return this._UomEntry;
			}
			set
			{
				if ((this._UomEntry != value))
				{
					this._UomEntry = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodProducto", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CodProducto
		{
			get
			{
				return this._CodProducto;
			}
			set
			{
				if ((this._CodProducto != value))
				{
					this._CodProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Producto", DbType="NVarChar(200)")]
		public string Producto
		{
			get
			{
				return this._Producto;
			}
			set
			{
				if ((this._Producto != value))
				{
					this._Producto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Int")]
		public System.Nullable<int> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Impuesto", DbType="NVarChar(8)")]
		public string Impuesto
		{
			get
			{
				return this._Impuesto;
			}
			set
			{
				if ((this._Impuesto != value))
				{
					this._Impuesto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rate", DbType="Int")]
		public System.Nullable<int> Rate
		{
			get
			{
				return this._Rate;
			}
			set
			{
				if ((this._Rate != value))
				{
					this._Rate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Neto", DbType="Int")]
		public System.Nullable<int> Neto
		{
			get
			{
				return this._Neto;
			}
			set
			{
				if ((this._Neto != value))
				{
					this._Neto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BcdCode", DbType="NVarChar(254) NOT NULL", CanBeNull=false)]
		public string BcdCode
		{
			get
			{
				return this._BcdCode;
			}
			set
			{
				if ((this._BcdCode != value))
				{
					this._BcdCode = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_SMM_ListaProductos_Unidades_GetProductos")]
	public partial class VW_SMM_ListaProductos_Unidades_GetProductos
	{
		
		private string _FechaActualizacion;
		
		private string _ItemCode;
		
		private string _ItemName;
		
		private string _BcdCode;
		
		private string _UomCode;
		
		private System.Nullable<int> _UomEntry;
		
		private System.Nullable<int> _CantidadxUM;
		
		private string _Marca;
		
		private string _Categoria;
		
		private string _SubCategoria;
		
		private string _CodProveedor;
		
		private string _Proveedor;
		
		private System.Nullable<int> _U_Multiplo;
		
		private System.Nullable<int> _U_VentaMinima;
		
		public VW_SMM_ListaProductos_Unidades_GetProductos()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaActualizacion", DbType="VarChar(59)")]
		public string FechaActualizacion
		{
			get
			{
				return this._FechaActualizacion;
			}
			set
			{
				if ((this._FechaActualizacion != value))
				{
					this._FechaActualizacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ItemCode
		{
			get
			{
				return this._ItemCode;
			}
			set
			{
				if ((this._ItemCode != value))
				{
					this._ItemCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemName", DbType="NVarChar(200)")]
		public string ItemName
		{
			get
			{
				return this._ItemName;
			}
			set
			{
				if ((this._ItemName != value))
				{
					this._ItemName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BcdCode", DbType="NVarChar(254)")]
		public string BcdCode
		{
			get
			{
				return this._BcdCode;
			}
			set
			{
				if ((this._BcdCode != value))
				{
					this._BcdCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UomCode", DbType="NVarChar(20)")]
		public string UomCode
		{
			get
			{
				return this._UomCode;
			}
			set
			{
				if ((this._UomCode != value))
				{
					this._UomCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UomEntry", DbType="Int")]
		public System.Nullable<int> UomEntry
		{
			get
			{
				return this._UomEntry;
			}
			set
			{
				if ((this._UomEntry != value))
				{
					this._UomEntry = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantidadxUM", DbType="Int")]
		public System.Nullable<int> CantidadxUM
		{
			get
			{
				return this._CantidadxUM;
			}
			set
			{
				if ((this._CantidadxUM != value))
				{
					this._CantidadxUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marca", DbType="NVarChar(50)")]
		public string Marca
		{
			get
			{
				return this._Marca;
			}
			set
			{
				if ((this._Marca != value))
				{
					this._Marca = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="NVarChar(100)")]
		public string Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this._Categoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubCategoria", DbType="NVarChar(100)")]
		public string SubCategoria
		{
			get
			{
				return this._SubCategoria;
			}
			set
			{
				if ((this._SubCategoria != value))
				{
					this._SubCategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodProveedor", DbType="NVarChar(15)")]
		public string CodProveedor
		{
			get
			{
				return this._CodProveedor;
			}
			set
			{
				if ((this._CodProveedor != value))
				{
					this._CodProveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Proveedor", DbType="NVarChar(100)")]
		public string Proveedor
		{
			get
			{
				return this._Proveedor;
			}
			set
			{
				if ((this._Proveedor != value))
				{
					this._Proveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_Multiplo", DbType="Int")]
		public System.Nullable<int> U_Multiplo
		{
			get
			{
				return this._U_Multiplo;
			}
			set
			{
				if ((this._U_Multiplo != value))
				{
					this._U_Multiplo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_VentaMinima", DbType="Int")]
		public System.Nullable<int> U_VentaMinima
		{
			get
			{
				return this._U_VentaMinima;
			}
			set
			{
				if ((this._U_VentaMinima != value))
				{
					this._U_VentaMinima = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
