#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBMermasRecepcion
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CVT_CONTROL_BIO")]
	public partial class DBMLCVTControlBIODataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Insertpers_person(pers_person instance);
    partial void Updatepers_person(pers_person instance);
    partial void Deletepers_person(pers_person instance);
    partial void Insertauth_department(auth_department instance);
    partial void Updateauth_department(auth_department instance);
    partial void Deleteauth_department(auth_department instance);
    partial void Insertacc_level(acc_level instance);
    partial void Updateacc_level(acc_level instance);
    partial void Deleteacc_level(acc_level instance);
    #endregion
		
		public DBMLCVTControlBIODataContext() : 
				base(global::DBMermasRecepcion.Properties.Settings.Default.CVT_CONTROL_BIOConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBMLCVTControlBIODataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBMLCVTControlBIODataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBMLCVTControlBIODataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBMLCVTControlBIODataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<pers_person> pers_person
		{
			get
			{
				return this.GetTable<pers_person>();
			}
		}
		
		public System.Data.Linq.Table<auth_department> auth_department
		{
			get
			{
				return this.GetTable<auth_department>();
			}
		}
		
		public System.Data.Linq.Table<CVT_VW_DatosPersonal> CVT_VW_DatosPersonal
		{
			get
			{
				return this.GetTable<CVT_VW_DatosPersonal>();
			}
		}
		
		public System.Data.Linq.Table<acc_level> acc_level
		{
			get
			{
				return this.GetTable<acc_level>();
			}
		}
		
		public System.Data.Linq.Table<VW_EMPLEADOS_CVT> VW_EMPLEADOS_CVT
		{
			get
			{
				return this.GetTable<VW_EMPLEADOS_CVT>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pers_person")]
	public partial class pers_person : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _app_id;
		
		private string _bio_tbl_id;
		
		private string _company_id;
		
		private System.Nullable<System.DateTime> _create_time;
		
		private string _creater_code;
		
		private string _creater_id;
		
		private string _creater_name;
		
		private System.Nullable<int> _op_version;
		
		private System.Nullable<System.DateTime> _update_time;
		
		private string _updater_code;
		
		private string _updater_id;
		
		private string _updater_name;
		
		private System.Nullable<System.DateTime> _birthday;
		
		private string _car_plate;
		
		private string _auth_dept_id;
		
		private string _email;
		
		private System.Nullable<short> _exception_flag;
		
		private string _gender;
		
		private System.Nullable<System.DateTime> _hire_date;
		
		private string _id_card;
		
		private string _id_card_physical_no;
		
		private string _is_from;
		
		private System.Nullable<bool> _is_sendmail;
		
		private string _last_name;
		
		private string _mobile_phone;
		
		private string _name;
		
		private string _name_spell;
		
		private string _person_pwd;
		
		private System.Nullable<short> _person_type;
		
		private string _photo_path;
		
		private string _pin;
		
		private System.Nullable<bool> _pin_letter;
		
		private string _self_pwd;
		
		private string _ssn;
		
		private System.Nullable<short> _status;
		
		private string _position_id;
		
		private System.Nullable<int> _pers_login_limit;
		
		private System.Nullable<bool> _send_sms;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void Onapp_idChanging(string value);
    partial void Onapp_idChanged();
    partial void Onbio_tbl_idChanging(string value);
    partial void Onbio_tbl_idChanged();
    partial void Oncompany_idChanging(string value);
    partial void Oncompany_idChanged();
    partial void Oncreate_timeChanging(System.Nullable<System.DateTime> value);
    partial void Oncreate_timeChanged();
    partial void Oncreater_codeChanging(string value);
    partial void Oncreater_codeChanged();
    partial void Oncreater_idChanging(string value);
    partial void Oncreater_idChanged();
    partial void Oncreater_nameChanging(string value);
    partial void Oncreater_nameChanged();
    partial void Onop_versionChanging(System.Nullable<int> value);
    partial void Onop_versionChanged();
    partial void Onupdate_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onupdate_timeChanged();
    partial void Onupdater_codeChanging(string value);
    partial void Onupdater_codeChanged();
    partial void Onupdater_idChanging(string value);
    partial void Onupdater_idChanged();
    partial void Onupdater_nameChanging(string value);
    partial void Onupdater_nameChanged();
    partial void OnbirthdayChanging(System.Nullable<System.DateTime> value);
    partial void OnbirthdayChanged();
    partial void Oncar_plateChanging(string value);
    partial void Oncar_plateChanged();
    partial void Onauth_dept_idChanging(string value);
    partial void Onauth_dept_idChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onexception_flagChanging(System.Nullable<short> value);
    partial void Onexception_flagChanged();
    partial void OngenderChanging(string value);
    partial void OngenderChanged();
    partial void Onhire_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onhire_dateChanged();
    partial void Onid_cardChanging(string value);
    partial void Onid_cardChanged();
    partial void Onid_card_physical_noChanging(string value);
    partial void Onid_card_physical_noChanged();
    partial void Onis_fromChanging(string value);
    partial void Onis_fromChanged();
    partial void Onis_sendmailChanging(System.Nullable<bool> value);
    partial void Onis_sendmailChanged();
    partial void Onlast_nameChanging(string value);
    partial void Onlast_nameChanged();
    partial void Onmobile_phoneChanging(string value);
    partial void Onmobile_phoneChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Onname_spellChanging(string value);
    partial void Onname_spellChanged();
    partial void Onperson_pwdChanging(string value);
    partial void Onperson_pwdChanged();
    partial void Onperson_typeChanging(System.Nullable<short> value);
    partial void Onperson_typeChanged();
    partial void Onphoto_pathChanging(string value);
    partial void Onphoto_pathChanged();
    partial void OnpinChanging(string value);
    partial void OnpinChanged();
    partial void Onpin_letterChanging(System.Nullable<bool> value);
    partial void Onpin_letterChanged();
    partial void Onself_pwdChanging(string value);
    partial void Onself_pwdChanged();
    partial void OnssnChanging(string value);
    partial void OnssnChanged();
    partial void OnstatusChanging(System.Nullable<short> value);
    partial void OnstatusChanged();
    partial void Onposition_idChanging(string value);
    partial void Onposition_idChanged();
    partial void Onpers_login_limitChanging(System.Nullable<int> value);
    partial void Onpers_login_limitChanged();
    partial void Onsend_smsChanging(System.Nullable<bool> value);
    partial void Onsend_smsChanged();
    #endregion
		
		public pers_person()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_app_id", DbType="NVarChar(255)")]
		public string app_id
		{
			get
			{
				return this._app_id;
			}
			set
			{
				if ((this._app_id != value))
				{
					this.Onapp_idChanging(value);
					this.SendPropertyChanging();
					this._app_id = value;
					this.SendPropertyChanged("app_id");
					this.Onapp_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bio_tbl_id", DbType="NVarChar(255)")]
		public string bio_tbl_id
		{
			get
			{
				return this._bio_tbl_id;
			}
			set
			{
				if ((this._bio_tbl_id != value))
				{
					this.Onbio_tbl_idChanging(value);
					this.SendPropertyChanging();
					this._bio_tbl_id = value;
					this.SendPropertyChanged("bio_tbl_id");
					this.Onbio_tbl_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_company_id", DbType="NVarChar(255)")]
		public string company_id
		{
			get
			{
				return this._company_id;
			}
			set
			{
				if ((this._company_id != value))
				{
					this.Oncompany_idChanging(value);
					this.SendPropertyChanging();
					this._company_id = value;
					this.SendPropertyChanged("company_id");
					this.Oncompany_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> create_time
		{
			get
			{
				return this._create_time;
			}
			set
			{
				if ((this._create_time != value))
				{
					this.Oncreate_timeChanging(value);
					this.SendPropertyChanging();
					this._create_time = value;
					this.SendPropertyChanged("create_time");
					this.Oncreate_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creater_code", DbType="NVarChar(100)")]
		public string creater_code
		{
			get
			{
				return this._creater_code;
			}
			set
			{
				if ((this._creater_code != value))
				{
					this.Oncreater_codeChanging(value);
					this.SendPropertyChanging();
					this._creater_code = value;
					this.SendPropertyChanged("creater_code");
					this.Oncreater_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creater_id", DbType="NVarChar(50)")]
		public string creater_id
		{
			get
			{
				return this._creater_id;
			}
			set
			{
				if ((this._creater_id != value))
				{
					this.Oncreater_idChanging(value);
					this.SendPropertyChanging();
					this._creater_id = value;
					this.SendPropertyChanged("creater_id");
					this.Oncreater_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creater_name", DbType="NVarChar(100)")]
		public string creater_name
		{
			get
			{
				return this._creater_name;
			}
			set
			{
				if ((this._creater_name != value))
				{
					this.Oncreater_nameChanging(value);
					this.SendPropertyChanging();
					this._creater_name = value;
					this.SendPropertyChanged("creater_name");
					this.Oncreater_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_op_version", DbType="Int")]
		public System.Nullable<int> op_version
		{
			get
			{
				return this._op_version;
			}
			set
			{
				if ((this._op_version != value))
				{
					this.Onop_versionChanging(value);
					this.SendPropertyChanging();
					this._op_version = value;
					this.SendPropertyChanged("op_version");
					this.Onop_versionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> update_time
		{
			get
			{
				return this._update_time;
			}
			set
			{
				if ((this._update_time != value))
				{
					this.Onupdate_timeChanging(value);
					this.SendPropertyChanging();
					this._update_time = value;
					this.SendPropertyChanged("update_time");
					this.Onupdate_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updater_code", DbType="NVarChar(100)")]
		public string updater_code
		{
			get
			{
				return this._updater_code;
			}
			set
			{
				if ((this._updater_code != value))
				{
					this.Onupdater_codeChanging(value);
					this.SendPropertyChanging();
					this._updater_code = value;
					this.SendPropertyChanged("updater_code");
					this.Onupdater_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updater_id", DbType="NVarChar(100)")]
		public string updater_id
		{
			get
			{
				return this._updater_id;
			}
			set
			{
				if ((this._updater_id != value))
				{
					this.Onupdater_idChanging(value);
					this.SendPropertyChanging();
					this._updater_id = value;
					this.SendPropertyChanged("updater_id");
					this.Onupdater_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updater_name", DbType="NVarChar(100)")]
		public string updater_name
		{
			get
			{
				return this._updater_name;
			}
			set
			{
				if ((this._updater_name != value))
				{
					this.Onupdater_nameChanging(value);
					this.SendPropertyChanging();
					this._updater_name = value;
					this.SendPropertyChanged("updater_name");
					this.Onupdater_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthday", DbType="DateTime")]
		public System.Nullable<System.DateTime> birthday
		{
			get
			{
				return this._birthday;
			}
			set
			{
				if ((this._birthday != value))
				{
					this.OnbirthdayChanging(value);
					this.SendPropertyChanging();
					this._birthday = value;
					this.SendPropertyChanged("birthday");
					this.OnbirthdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car_plate", DbType="NVarChar(20)")]
		public string car_plate
		{
			get
			{
				return this._car_plate;
			}
			set
			{
				if ((this._car_plate != value))
				{
					this.Oncar_plateChanging(value);
					this.SendPropertyChanging();
					this._car_plate = value;
					this.SendPropertyChanged("car_plate");
					this.Oncar_plateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_auth_dept_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string auth_dept_id
		{
			get
			{
				return this._auth_dept_id;
			}
			set
			{
				if ((this._auth_dept_id != value))
				{
					this.Onauth_dept_idChanging(value);
					this.SendPropertyChanging();
					this._auth_dept_id = value;
					this.SendPropertyChanged("auth_dept_id");
					this.Onauth_dept_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exception_flag", DbType="SmallInt")]
		public System.Nullable<short> exception_flag
		{
			get
			{
				return this._exception_flag;
			}
			set
			{
				if ((this._exception_flag != value))
				{
					this.Onexception_flagChanging(value);
					this.SendPropertyChanging();
					this._exception_flag = value;
					this.SendPropertyChanged("exception_flag");
					this.Onexception_flagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="NVarChar(1)")]
		public string gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this.OngenderChanging(value);
					this.SendPropertyChanging();
					this._gender = value;
					this.SendPropertyChanged("gender");
					this.OngenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hire_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> hire_date
		{
			get
			{
				return this._hire_date;
			}
			set
			{
				if ((this._hire_date != value))
				{
					this.Onhire_dateChanging(value);
					this.SendPropertyChanging();
					this._hire_date = value;
					this.SendPropertyChanged("hire_date");
					this.Onhire_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_card", DbType="NVarChar(20)")]
		public string id_card
		{
			get
			{
				return this._id_card;
			}
			set
			{
				if ((this._id_card != value))
				{
					this.Onid_cardChanging(value);
					this.SendPropertyChanging();
					this._id_card = value;
					this.SendPropertyChanged("id_card");
					this.Onid_cardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_card_physical_no", DbType="NVarChar(50)")]
		public string id_card_physical_no
		{
			get
			{
				return this._id_card_physical_no;
			}
			set
			{
				if ((this._id_card_physical_no != value))
				{
					this.Onid_card_physical_noChanging(value);
					this.SendPropertyChanging();
					this._id_card_physical_no = value;
					this.SendPropertyChanged("id_card_physical_no");
					this.Onid_card_physical_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_from", DbType="NVarChar(100)")]
		public string is_from
		{
			get
			{
				return this._is_from;
			}
			set
			{
				if ((this._is_from != value))
				{
					this.Onis_fromChanging(value);
					this.SendPropertyChanging();
					this._is_from = value;
					this.SendPropertyChanged("is_from");
					this.Onis_fromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_sendmail", DbType="Bit")]
		public System.Nullable<bool> is_sendmail
		{
			get
			{
				return this._is_sendmail;
			}
			set
			{
				if ((this._is_sendmail != value))
				{
					this.Onis_sendmailChanging(value);
					this.SendPropertyChanging();
					this._is_sendmail = value;
					this.SendPropertyChanged("is_sendmail");
					this.Onis_sendmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_name", DbType="NVarChar(50)")]
		public string last_name
		{
			get
			{
				return this._last_name;
			}
			set
			{
				if ((this._last_name != value))
				{
					this.Onlast_nameChanging(value);
					this.SendPropertyChanging();
					this._last_name = value;
					this.SendPropertyChanged("last_name");
					this.Onlast_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobile_phone", DbType="NVarChar(20)")]
		public string mobile_phone
		{
			get
			{
				return this._mobile_phone;
			}
			set
			{
				if ((this._mobile_phone != value))
				{
					this.Onmobile_phoneChanging(value);
					this.SendPropertyChanging();
					this._mobile_phone = value;
					this.SendPropertyChanged("mobile_phone");
					this.Onmobile_phoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_spell", DbType="NVarChar(420)")]
		public string name_spell
		{
			get
			{
				return this._name_spell;
			}
			set
			{
				if ((this._name_spell != value))
				{
					this.Onname_spellChanging(value);
					this.SendPropertyChanging();
					this._name_spell = value;
					this.SendPropertyChanged("name_spell");
					this.Onname_spellChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_person_pwd", DbType="NVarChar(32)")]
		public string person_pwd
		{
			get
			{
				return this._person_pwd;
			}
			set
			{
				if ((this._person_pwd != value))
				{
					this.Onperson_pwdChanging(value);
					this.SendPropertyChanging();
					this._person_pwd = value;
					this.SendPropertyChanged("person_pwd");
					this.Onperson_pwdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_person_type", DbType="SmallInt")]
		public System.Nullable<short> person_type
		{
			get
			{
				return this._person_type;
			}
			set
			{
				if ((this._person_type != value))
				{
					this.Onperson_typeChanging(value);
					this.SendPropertyChanging();
					this._person_type = value;
					this.SendPropertyChanged("person_type");
					this.Onperson_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_photo_path", DbType="NVarChar(200)")]
		public string photo_path
		{
			get
			{
				return this._photo_path;
			}
			set
			{
				if ((this._photo_path != value))
				{
					this.Onphoto_pathChanging(value);
					this.SendPropertyChanging();
					this._photo_path = value;
					this.SendPropertyChanged("photo_path");
					this.Onphoto_pathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pin", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string pin
		{
			get
			{
				return this._pin;
			}
			set
			{
				if ((this._pin != value))
				{
					this.OnpinChanging(value);
					this.SendPropertyChanging();
					this._pin = value;
					this.SendPropertyChanged("pin");
					this.OnpinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pin_letter", DbType="Bit")]
		public System.Nullable<bool> pin_letter
		{
			get
			{
				return this._pin_letter;
			}
			set
			{
				if ((this._pin_letter != value))
				{
					this.Onpin_letterChanging(value);
					this.SendPropertyChanging();
					this._pin_letter = value;
					this.SendPropertyChanged("pin_letter");
					this.Onpin_letterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_self_pwd", DbType="NVarChar(32)")]
		public string self_pwd
		{
			get
			{
				return this._self_pwd;
			}
			set
			{
				if ((this._self_pwd != value))
				{
					this.Onself_pwdChanging(value);
					this.SendPropertyChanging();
					this._self_pwd = value;
					this.SendPropertyChanged("self_pwd");
					this.Onself_pwdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ssn", DbType="NVarChar(20)")]
		public string ssn
		{
			get
			{
				return this._ssn;
			}
			set
			{
				if ((this._ssn != value))
				{
					this.OnssnChanging(value);
					this.SendPropertyChanging();
					this._ssn = value;
					this.SendPropertyChanged("ssn");
					this.OnssnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="SmallInt")]
		public System.Nullable<short> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_position_id", DbType="NVarChar(50)")]
		public string position_id
		{
			get
			{
				return this._position_id;
			}
			set
			{
				if ((this._position_id != value))
				{
					this.Onposition_idChanging(value);
					this.SendPropertyChanging();
					this._position_id = value;
					this.SendPropertyChanged("position_id");
					this.Onposition_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pers_login_limit", DbType="Int")]
		public System.Nullable<int> pers_login_limit
		{
			get
			{
				return this._pers_login_limit;
			}
			set
			{
				if ((this._pers_login_limit != value))
				{
					this.Onpers_login_limitChanging(value);
					this.SendPropertyChanging();
					this._pers_login_limit = value;
					this.SendPropertyChanged("pers_login_limit");
					this.Onpers_login_limitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_send_sms", DbType="Bit")]
		public System.Nullable<bool> send_sms
		{
			get
			{
				return this._send_sms;
			}
			set
			{
				if ((this._send_sms != value))
				{
					this.Onsend_smsChanging(value);
					this.SendPropertyChanging();
					this._send_sms = value;
					this.SendPropertyChanged("send_sms");
					this.Onsend_smsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.auth_department")]
	public partial class auth_department : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _app_id;
		
		private string _bio_tbl_id;
		
		private string _company_id;
		
		private System.Nullable<System.DateTime> _create_time;
		
		private string _creater_code;
		
		private string _creater_id;
		
		private string _creater_name;
		
		private System.Nullable<int> _op_version;
		
		private System.Nullable<System.DateTime> _update_time;
		
		private string _updater_code;
		
		private string _updater_id;
		
		private string _updater_name;
		
		private string _code;
		
		private string _init_code;
		
		private string _name;
		
		private System.Nullable<int> _sort;
		
		private string _parent_id;
		
		private EntitySet<auth_department> _auth_department2;
		
		private EntityRef<auth_department> _auth_department1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void Onapp_idChanging(string value);
    partial void Onapp_idChanged();
    partial void Onbio_tbl_idChanging(string value);
    partial void Onbio_tbl_idChanged();
    partial void Oncompany_idChanging(string value);
    partial void Oncompany_idChanged();
    partial void Oncreate_timeChanging(System.Nullable<System.DateTime> value);
    partial void Oncreate_timeChanged();
    partial void Oncreater_codeChanging(string value);
    partial void Oncreater_codeChanged();
    partial void Oncreater_idChanging(string value);
    partial void Oncreater_idChanged();
    partial void Oncreater_nameChanging(string value);
    partial void Oncreater_nameChanged();
    partial void Onop_versionChanging(System.Nullable<int> value);
    partial void Onop_versionChanged();
    partial void Onupdate_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onupdate_timeChanged();
    partial void Onupdater_codeChanging(string value);
    partial void Onupdater_codeChanged();
    partial void Onupdater_idChanging(string value);
    partial void Onupdater_idChanged();
    partial void Onupdater_nameChanging(string value);
    partial void Onupdater_nameChanged();
    partial void OncodeChanging(string value);
    partial void OncodeChanged();
    partial void Oninit_codeChanging(string value);
    partial void Oninit_codeChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnsortChanging(System.Nullable<int> value);
    partial void OnsortChanged();
    partial void Onparent_idChanging(string value);
    partial void Onparent_idChanged();
    #endregion
		
		public auth_department()
		{
			this._auth_department2 = new EntitySet<auth_department>(new Action<auth_department>(this.attach_auth_department2), new Action<auth_department>(this.detach_auth_department2));
			this._auth_department1 = default(EntityRef<auth_department>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_app_id", DbType="NVarChar(255)")]
		public string app_id
		{
			get
			{
				return this._app_id;
			}
			set
			{
				if ((this._app_id != value))
				{
					this.Onapp_idChanging(value);
					this.SendPropertyChanging();
					this._app_id = value;
					this.SendPropertyChanged("app_id");
					this.Onapp_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bio_tbl_id", DbType="NVarChar(255)")]
		public string bio_tbl_id
		{
			get
			{
				return this._bio_tbl_id;
			}
			set
			{
				if ((this._bio_tbl_id != value))
				{
					this.Onbio_tbl_idChanging(value);
					this.SendPropertyChanging();
					this._bio_tbl_id = value;
					this.SendPropertyChanged("bio_tbl_id");
					this.Onbio_tbl_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_company_id", DbType="NVarChar(255)")]
		public string company_id
		{
			get
			{
				return this._company_id;
			}
			set
			{
				if ((this._company_id != value))
				{
					this.Oncompany_idChanging(value);
					this.SendPropertyChanging();
					this._company_id = value;
					this.SendPropertyChanged("company_id");
					this.Oncompany_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> create_time
		{
			get
			{
				return this._create_time;
			}
			set
			{
				if ((this._create_time != value))
				{
					this.Oncreate_timeChanging(value);
					this.SendPropertyChanging();
					this._create_time = value;
					this.SendPropertyChanged("create_time");
					this.Oncreate_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creater_code", DbType="NVarChar(100)")]
		public string creater_code
		{
			get
			{
				return this._creater_code;
			}
			set
			{
				if ((this._creater_code != value))
				{
					this.Oncreater_codeChanging(value);
					this.SendPropertyChanging();
					this._creater_code = value;
					this.SendPropertyChanged("creater_code");
					this.Oncreater_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creater_id", DbType="NVarChar(50)")]
		public string creater_id
		{
			get
			{
				return this._creater_id;
			}
			set
			{
				if ((this._creater_id != value))
				{
					this.Oncreater_idChanging(value);
					this.SendPropertyChanging();
					this._creater_id = value;
					this.SendPropertyChanged("creater_id");
					this.Oncreater_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creater_name", DbType="NVarChar(100)")]
		public string creater_name
		{
			get
			{
				return this._creater_name;
			}
			set
			{
				if ((this._creater_name != value))
				{
					this.Oncreater_nameChanging(value);
					this.SendPropertyChanging();
					this._creater_name = value;
					this.SendPropertyChanged("creater_name");
					this.Oncreater_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_op_version", DbType="Int")]
		public System.Nullable<int> op_version
		{
			get
			{
				return this._op_version;
			}
			set
			{
				if ((this._op_version != value))
				{
					this.Onop_versionChanging(value);
					this.SendPropertyChanging();
					this._op_version = value;
					this.SendPropertyChanged("op_version");
					this.Onop_versionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> update_time
		{
			get
			{
				return this._update_time;
			}
			set
			{
				if ((this._update_time != value))
				{
					this.Onupdate_timeChanging(value);
					this.SendPropertyChanging();
					this._update_time = value;
					this.SendPropertyChanged("update_time");
					this.Onupdate_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updater_code", DbType="NVarChar(100)")]
		public string updater_code
		{
			get
			{
				return this._updater_code;
			}
			set
			{
				if ((this._updater_code != value))
				{
					this.Onupdater_codeChanging(value);
					this.SendPropertyChanging();
					this._updater_code = value;
					this.SendPropertyChanged("updater_code");
					this.Onupdater_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updater_id", DbType="NVarChar(100)")]
		public string updater_id
		{
			get
			{
				return this._updater_id;
			}
			set
			{
				if ((this._updater_id != value))
				{
					this.Onupdater_idChanging(value);
					this.SendPropertyChanging();
					this._updater_id = value;
					this.SendPropertyChanged("updater_id");
					this.Onupdater_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updater_name", DbType="NVarChar(100)")]
		public string updater_name
		{
			get
			{
				return this._updater_name;
			}
			set
			{
				if ((this._updater_name != value))
				{
					this.Onupdater_nameChanging(value);
					this.SendPropertyChanging();
					this._updater_name = value;
					this.SendPropertyChanged("updater_name");
					this.Onupdater_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this.OncodeChanging(value);
					this.SendPropertyChanging();
					this._code = value;
					this.SendPropertyChanged("code");
					this.OncodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_init_code", DbType="NVarChar(30)")]
		public string init_code
		{
			get
			{
				return this._init_code;
			}
			set
			{
				if ((this._init_code != value))
				{
					this.Oninit_codeChanging(value);
					this.SendPropertyChanging();
					this._init_code = value;
					this.SendPropertyChanged("init_code");
					this.Oninit_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sort", DbType="Int")]
		public System.Nullable<int> sort
		{
			get
			{
				return this._sort;
			}
			set
			{
				if ((this._sort != value))
				{
					this.OnsortChanging(value);
					this.SendPropertyChanging();
					this._sort = value;
					this.SendPropertyChanged("sort");
					this.OnsortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent_id", DbType="NVarChar(50)")]
		public string parent_id
		{
			get
			{
				return this._parent_id;
			}
			set
			{
				if ((this._parent_id != value))
				{
					if (this._auth_department1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onparent_idChanging(value);
					this.SendPropertyChanging();
					this._parent_id = value;
					this.SendPropertyChanged("parent_id");
					this.Onparent_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="auth_department_auth_department", Storage="_auth_department2", ThisKey="id", OtherKey="parent_id")]
		public EntitySet<auth_department> auth_department2
		{
			get
			{
				return this._auth_department2;
			}
			set
			{
				this._auth_department2.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="auth_department_auth_department", Storage="_auth_department1", ThisKey="parent_id", OtherKey="id", IsForeignKey=true)]
		public auth_department auth_department1
		{
			get
			{
				return this._auth_department1.Entity;
			}
			set
			{
				auth_department previousValue = this._auth_department1.Entity;
				if (((previousValue != value) 
							|| (this._auth_department1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._auth_department1.Entity = null;
						previousValue.auth_department2.Remove(this);
					}
					this._auth_department1.Entity = value;
					if ((value != null))
					{
						value.auth_department2.Add(this);
						this._parent_id = value.id;
					}
					else
					{
						this._parent_id = default(string);
					}
					this.SendPropertyChanged("auth_department1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_auth_department2(auth_department entity)
		{
			this.SendPropertyChanging();
			entity.auth_department1 = this;
		}
		
		private void detach_auth_department2(auth_department entity)
		{
			this.SendPropertyChanging();
			entity.auth_department1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CVT_VW_DatosPersonal")]
	public partial class CVT_VW_DatosPersonal
	{
		
		private string _RUN;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private string _Genero;
		
		private string _Departamento;
		
		private string _Domicilio;
		
		private string _Cargo;
		
		private System.Nullable<System.DateTime> _FechaCreacion;
		
		private string _NivelAcceso;
		
		public CVT_VW_DatosPersonal()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RUN", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string RUN
		{
			get
			{
				return this._RUN;
			}
			set
			{
				if ((this._RUN != value))
				{
					this._RUN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="NVarChar(50)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Genero", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string Genero
		{
			get
			{
				return this._Genero;
			}
			set
			{
				if ((this._Genero != value))
				{
					this._Genero = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Departamento", DbType="NVarChar(100)")]
		public string Departamento
		{
			get
			{
				return this._Departamento;
			}
			set
			{
				if ((this._Departamento != value))
				{
					this._Departamento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Domicilio", DbType="NVarChar(255)")]
		public string Domicilio
		{
			get
			{
				return this._Domicilio;
			}
			set
			{
				if ((this._Domicilio != value))
				{
					this._Domicilio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cargo", DbType="NVarChar(255)")]
		public string Cargo
		{
			get
			{
				return this._Cargo;
			}
			set
			{
				if ((this._Cargo != value))
				{
					this._Cargo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this._FechaCreacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NivelAcceso", DbType="NVarChar(50)")]
		public string NivelAcceso
		{
			get
			{
				return this._NivelAcceso;
			}
			set
			{
				if ((this._NivelAcceso != value))
				{
					this._NivelAcceso = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.acc_level")]
	public partial class acc_level : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _app_id;
		
		private string _bio_tbl_id;
		
		private string _company_id;
		
		private System.Nullable<System.DateTime> _create_time;
		
		private string _creater_code;
		
		private string _creater_id;
		
		private string _creater_name;
		
		private System.Nullable<int> _op_version;
		
		private System.Nullable<System.DateTime> _update_time;
		
		private string _updater_code;
		
		private string _updater_id;
		
		private string _updater_name;
		
		private string _auth_area_id;
		
		private System.Nullable<bool> _init_flag;
		
		private string _name;
		
		private string _timeseg_id;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void Onapp_idChanging(string value);
    partial void Onapp_idChanged();
    partial void Onbio_tbl_idChanging(string value);
    partial void Onbio_tbl_idChanged();
    partial void Oncompany_idChanging(string value);
    partial void Oncompany_idChanged();
    partial void Oncreate_timeChanging(System.Nullable<System.DateTime> value);
    partial void Oncreate_timeChanged();
    partial void Oncreater_codeChanging(string value);
    partial void Oncreater_codeChanged();
    partial void Oncreater_idChanging(string value);
    partial void Oncreater_idChanged();
    partial void Oncreater_nameChanging(string value);
    partial void Oncreater_nameChanged();
    partial void Onop_versionChanging(System.Nullable<int> value);
    partial void Onop_versionChanged();
    partial void Onupdate_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onupdate_timeChanged();
    partial void Onupdater_codeChanging(string value);
    partial void Onupdater_codeChanged();
    partial void Onupdater_idChanging(string value);
    partial void Onupdater_idChanged();
    partial void Onupdater_nameChanging(string value);
    partial void Onupdater_nameChanged();
    partial void Onauth_area_idChanging(string value);
    partial void Onauth_area_idChanged();
    partial void Oninit_flagChanging(System.Nullable<bool> value);
    partial void Oninit_flagChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Ontimeseg_idChanging(string value);
    partial void Ontimeseg_idChanged();
    #endregion
		
		public acc_level()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_app_id", DbType="NVarChar(255)")]
		public string app_id
		{
			get
			{
				return this._app_id;
			}
			set
			{
				if ((this._app_id != value))
				{
					this.Onapp_idChanging(value);
					this.SendPropertyChanging();
					this._app_id = value;
					this.SendPropertyChanged("app_id");
					this.Onapp_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bio_tbl_id", DbType="NVarChar(255)")]
		public string bio_tbl_id
		{
			get
			{
				return this._bio_tbl_id;
			}
			set
			{
				if ((this._bio_tbl_id != value))
				{
					this.Onbio_tbl_idChanging(value);
					this.SendPropertyChanging();
					this._bio_tbl_id = value;
					this.SendPropertyChanged("bio_tbl_id");
					this.Onbio_tbl_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_company_id", DbType="NVarChar(255)")]
		public string company_id
		{
			get
			{
				return this._company_id;
			}
			set
			{
				if ((this._company_id != value))
				{
					this.Oncompany_idChanging(value);
					this.SendPropertyChanging();
					this._company_id = value;
					this.SendPropertyChanged("company_id");
					this.Oncompany_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> create_time
		{
			get
			{
				return this._create_time;
			}
			set
			{
				if ((this._create_time != value))
				{
					this.Oncreate_timeChanging(value);
					this.SendPropertyChanging();
					this._create_time = value;
					this.SendPropertyChanged("create_time");
					this.Oncreate_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creater_code", DbType="NVarChar(100)")]
		public string creater_code
		{
			get
			{
				return this._creater_code;
			}
			set
			{
				if ((this._creater_code != value))
				{
					this.Oncreater_codeChanging(value);
					this.SendPropertyChanging();
					this._creater_code = value;
					this.SendPropertyChanged("creater_code");
					this.Oncreater_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creater_id", DbType="NVarChar(50)")]
		public string creater_id
		{
			get
			{
				return this._creater_id;
			}
			set
			{
				if ((this._creater_id != value))
				{
					this.Oncreater_idChanging(value);
					this.SendPropertyChanging();
					this._creater_id = value;
					this.SendPropertyChanged("creater_id");
					this.Oncreater_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creater_name", DbType="NVarChar(100)")]
		public string creater_name
		{
			get
			{
				return this._creater_name;
			}
			set
			{
				if ((this._creater_name != value))
				{
					this.Oncreater_nameChanging(value);
					this.SendPropertyChanging();
					this._creater_name = value;
					this.SendPropertyChanged("creater_name");
					this.Oncreater_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_op_version", DbType="Int")]
		public System.Nullable<int> op_version
		{
			get
			{
				return this._op_version;
			}
			set
			{
				if ((this._op_version != value))
				{
					this.Onop_versionChanging(value);
					this.SendPropertyChanging();
					this._op_version = value;
					this.SendPropertyChanged("op_version");
					this.Onop_versionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> update_time
		{
			get
			{
				return this._update_time;
			}
			set
			{
				if ((this._update_time != value))
				{
					this.Onupdate_timeChanging(value);
					this.SendPropertyChanging();
					this._update_time = value;
					this.SendPropertyChanged("update_time");
					this.Onupdate_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updater_code", DbType="NVarChar(100)")]
		public string updater_code
		{
			get
			{
				return this._updater_code;
			}
			set
			{
				if ((this._updater_code != value))
				{
					this.Onupdater_codeChanging(value);
					this.SendPropertyChanging();
					this._updater_code = value;
					this.SendPropertyChanged("updater_code");
					this.Onupdater_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updater_id", DbType="NVarChar(100)")]
		public string updater_id
		{
			get
			{
				return this._updater_id;
			}
			set
			{
				if ((this._updater_id != value))
				{
					this.Onupdater_idChanging(value);
					this.SendPropertyChanging();
					this._updater_id = value;
					this.SendPropertyChanged("updater_id");
					this.Onupdater_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updater_name", DbType="NVarChar(100)")]
		public string updater_name
		{
			get
			{
				return this._updater_name;
			}
			set
			{
				if ((this._updater_name != value))
				{
					this.Onupdater_nameChanging(value);
					this.SendPropertyChanging();
					this._updater_name = value;
					this.SendPropertyChanged("updater_name");
					this.Onupdater_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_auth_area_id", DbType="NVarChar(255)")]
		public string auth_area_id
		{
			get
			{
				return this._auth_area_id;
			}
			set
			{
				if ((this._auth_area_id != value))
				{
					this.Onauth_area_idChanging(value);
					this.SendPropertyChanging();
					this._auth_area_id = value;
					this.SendPropertyChanged("auth_area_id");
					this.Onauth_area_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_init_flag", DbType="Bit")]
		public System.Nullable<bool> init_flag
		{
			get
			{
				return this._init_flag;
			}
			set
			{
				if ((this._init_flag != value))
				{
					this.Oninit_flagChanging(value);
					this.SendPropertyChanging();
					this._init_flag = value;
					this.SendPropertyChanged("init_flag");
					this.Oninit_flagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(30)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timeseg_id", DbType="NVarChar(50)")]
		public string timeseg_id
		{
			get
			{
				return this._timeseg_id;
			}
			set
			{
				if ((this._timeseg_id != value))
				{
					this.Ontimeseg_idChanging(value);
					this.SendPropertyChanging();
					this._timeseg_id = value;
					this.SendPropertyChanged("timeseg_id");
					this.Ontimeseg_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_EMPLEADOS_CVT")]
	public partial class VW_EMPLEADOS_CVT
	{
		
		private string _Apellido;
		
		private string _Nombre;
		
		private string _Run;
		
		private string _Depto;
		
		public VW_EMPLEADOS_CVT()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="NVarChar(50)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Run", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Run
		{
			get
			{
				return this._Run;
			}
			set
			{
				if ((this._Run != value))
				{
					this._Run = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Depto", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Depto
		{
			get
			{
				return this._Depto;
			}
			set
			{
				if ((this._Depto != value))
				{
					this._Depto = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
